server:
  port: 7070

spring:
  application:
    name: config-serve
  cloud:
    config:
      server:
        git:
          uri: https://github.com/guver71/PracticaDAD.git
          search-paths: config-data
          #username:
          #password:
          default-label: ms-config-serve
  security:
    user:
      name: root
      password: s3cr3t